# Trigger on main branch (equivalent to Azure DevOps trigger)
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  validate_and_generate_arm_template:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # Step 3: Install npm packages
      - name: Install npm package
        run: |
          cd $GITHUB_WORKSPACE # replace with folder containing package.json
          npm install

      # Step 4: Validate ADF resources
      - name: Validate ADF resources
        run: |
          cd $GITHUB_WORKSPACE
          npm run build validate $(pwd)/ /subscriptions/51df5574-3a71-4820-8787-73ec31f4d204/resourceGroups/Ani_practice/providers/Microsoft.DataFactory/factories/AniketDemo

      # Step 5: Validate and generate ARM template
      - name: Validate and Generate ARM template
        run: |
          cd $GITHUB_WORKSPACE
          npm run build export $(pwd)/ /subscriptions/51df5574-3a71-4820-8787-73ec31f4d204/resourceGroups/Ani_practice/providers/Microsoft.DataFactory/factories/AniketDemo "ArmTemplate"
          # If using preview build:
          # npm run build-preview export $(pwd)/ /subscriptions/51df5574-3a71-4820-8787-73ec31f4d204/resourceGroups/Ani_practice/providers/Microsoft.DataFactory/factories/AniketDemo "ArmTemplate"

      # Step 6: Upload ARM template as artifact
      - name: Upload ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArmTemplates
          path: $GITHUB_WORKSPACE/ArmTemplate
